openapi: 3.0.0
info:
  title: Video API
  version: 1.0.0
  description: Video API documentation

tags:
  - name: Testing
    description: API for clearing the database
  - name: Videos
    description: API for managing videos